on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15"
          cache: "npm"
      - run: npm -g up npm
      - run: npm  ci

  pack-and-release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.15"
          cache: "npm"

      - name: Update to latest npm (for node ver)
        run: npm -g up npm

      - name: Wrapped in plastic
        run: npm shrinkwrap

      - name: Create tarball
        run: |
          TARBALL=$(npm pack)
          echo "::set-output name=TARBALL::$TARBALL"
        id: pack
      - name: Create release and upload asset
        uses: softprops/action-gh-release@fb0163a75bee697a9cfec2c931801de7c7f10042
        with:
          files: ${{ steps.pack.outputs.TARBALL }}
